### ISSUE TITLE
Hemogenic extaction issues

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/WaterFlavourPack#2]
- Pawns with the hemogenic gene (in this case "Water Drinker") cannot be drained for blood (in this case water), possible fixed in the operation def, need to investigate
- Operation needs to rely on water, rather than blood loss. Needs a new hediff (something simple, not tiered like blood loss) simply "water drained" might work. Hediff ticks down like usual. No special mechanics needed

**Comment by keyz182** [comment]
I patched the first part in my PR, along with disabling the application of bloodloss. So should just need the new hediff.

**Comment by MrSamuelStreamer** [comment]
Added new hediff in [Hediffs](https://github.com/MrSamuelStreamer/WaterFlavourPack/blob/main/1.5/Defs/HediffDefs/MSS_Thirst_Hediffs_Local_Misc.xml) just needs attaching as a conditional to prevent surgery until it ticks down and disappears, and needs to be added after surgery
